plugins: jekyll-include-cache
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

title: All about Firmware 
description: Site covers journey of learning about firmware 
url: "https://username.github.io"
baseurl: "" # Leave this blank for user GitHub Pages
